version: "3"

services:
  website:
    image: istresearch/sentinel_tunnel:prototype
    build:
      context: .
    ports:
      - "12345:12345"
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
