name: Notify

on:
  discussion:
    types: [created, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Send notification
        uses: USA-RedDragon/telegram-notification@v1.0.0
        with:
          bot-token: ${{ secrets.TG_BOT_TOKEN }}
          chat-id: ${{ secrets.TG_CHAT_ID }}
